# Generated by Django 3.0 on 2022-12-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approvade',
            field=models.BooleanField(default=True),
        ),
    ]
